return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
    event = "VeryLazy",
	config = function()
		local configs = require("nvim-treesitter.configs")
		configs.setup({
			ensure_installed = {
				"bash",
				"c",
				"cmake",
				"cpp",
				"dockerfile",
				"go",
				"html",
				"java",
				"javascript",
				"kotlin",
				"latex",
				"lua",
				"make",
				"markdown",
				"markdown_inline",
				"python",
				"rust",
				"typescript",
				"typst",
				"yaml",
                "c_sharp",
                "comment",
                "css",
                "csv",
                "diff",
                "editorconfig",
                "gitignore",
                "hocon",
                "http",
                "hurl",
                "ini",
                "javadoc",
                "json",
                "luadoc",
                "regex",
                "scala",
                "sql",
                "vim",
                "vimdoc",
                "xml",
			},
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = false,
			},
		})
	end,
}
